# Generated by Django 5.2.12 on 2026-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('contenu', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=254)),
                ('tags', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
